### ISSUE TITLE
Update the README

### ISSUE THREAD

**Issue by siberov** [Fundamentals-KTH-CSC-2022-P3/DECIDE#49]
According to the grading criteria:

>Property: the repository is structured with appropriate folders and contains a good [README](https://yourbasic.org/algorithms/your-basic-api/#1-tell-me-what-this-thing-is). In addition to the contents of a normal README, your README also contains the statement of contributions.

So add the following:
- A short summary about the project.
- A statement of contributions.
- Information on how to setup the test config.

**Comment by alevarn** [comment]
Solved by #53
