### ISSUE TITLE
Assess and document our way of working

### ISSUE THREAD

**Issue by siberov** [Fundamentals-KTH-CSC-2022-P3/DECIDE#50]
Write one paragraph documenting our way of working, following page 58 in the [ESSENCE standard](https://www.omg.org/spec/Essence/1.2/PDF). Do this by evaluating the checklist on page 60 in the same document. 
Answer the following qustions:
- In what state are you in? Why? 
- What are obstacles to reach the next state?

Write this in Google Docs.

**Comment by alevarn** [comment]
Check it out here before I close the issue:
https://docs.google.com/document/d/1iywNeKTS13n_s4mHrE6r4-EKvVzWLqKpwtsrKsB-Lyw/edit#
