### ISSUE TITLE
RunTimeException thrown in unrelated class disrupts tests

### ISSUE THREAD

**Issue by SamuSoft** [Fundamentals-KTH-CSC-2022-P3/DECIDE#55]
Throwing of runtime exception in Triangle.class causes some tests to fail.

**Comment by siberov** [comment]
We have decided to allow triangles to have an area of 0, which will solve this problem. However, the `Point.vertexAngle`-method should throw an exception when any of the points coincide with the vertex. This would also allow several checks in the LIC-methods to be removed.

**Comment by siberov** [comment]
Checks to be removed are in:

- lic2
- lic3
- lic14

NB not sure that this list is exhaustive
